# Generated by Django 2.2.10 on 2020-03-02 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_image_source_set'),
        ('garden', '0002_auto_20200223_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Project')),
            ],
        ),
    ]
