# Generated by Django 2.2.10 on 2020-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_projectconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='sensorID',
            field=models.CharField(default='default_sensor', max_length=20),
        ),
    ]
