# Generated by Django 2.1.3 on 2018-11-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181112_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
