# Generated by Django 2.1.3 on 2018-12-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181221_1319'),
        ('blog', '0004_image_project'),
    ]

    operations = [
    ]
