# Generated by Django 2.1.3 on 2019-01-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190102_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='importance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
