# Generated by Django 2.1.3 on 2019-01-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_project_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_alt_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Image'),
        ),
    ]
