# Generated by Django 2.1.3 on 2019-01-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190104_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ManyToManyField(to='blog.Image'),
        ),
    ]
