# Generated by Django 2.1.3 on 2019-01-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190104_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='post',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
    ]
