# Generated by Django 2.2.4 on 2019-10-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190107_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source_set',
            field=models.TextField(blank=True, null=True),
        ),
    ]
