# Generated by Django 2.1.7 on 2019-03-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20190314_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='aloft_wind_direction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='aloft_wind_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_outdoor_humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_outdoor_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_pressure_millibars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
