# Generated by Django 2.1.7 on 2019-03-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20190314_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='cloud_coverage',
        ),
    ]
