# Generated by Django 2.1.7 on 2019-03-15 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_observation_cloud_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='cloud_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.Cloud_coverage_choices'),
        ),
    ]
