# Generated by Django 2.1.7 on 2019-03-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_observation_cloud_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precipitation_choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='observation',
            name='precipitation_observation',
        ),
    ]
