# Generated by Django 2.1.7 on 2019-03-15 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20190314_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='precipitation_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.Precipitation_choices'),
        ),
    ]
