# Generated by Django 2.1.7 on 2019-03-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_observation_precipitation_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='precipitation_choices',
            name='precipitation_type',
            field=models.CharField(default='No precipitation', max_length=255),
            preserve_default=False,
        ),
    ]
