# Generated by Django 2.1.7 on 2019-03-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_precipitation_choices_precipitation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phenomena_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenomena', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='observation',
            name='phenomena_observation',
        ),
    ]
