# Generated by Django 2.2.4 on 2019-08-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_observation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='observation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, default=39.9434, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, default=-82.9825, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
