# Generated by Django 2.2.4 on 2019-10-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_observation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='source_set',
            field=models.TextField(blank=True, null=True),
        ),
    ]
